server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_reserve?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl